## tests for cachematrix.R

source("cachematrix.R")
x<-makeCacheMatrix()
print("case 1: matrix x is not set")
b <- cacheSolve(x)
print("inv(x) is")
print(b)
print("#############################")
print("case 2: matrix x is set as [1,2;3,4]")
a <- matrix(1:4, nrow = 2, ncol = 2, byrow = TRUE)
x$set(a)
print("x is")
print(x$get())
b <- cacheSolve(x) 
print("inv(x) is")
print(b)
print("a %*% b is")
print(a %*% b)